### ISSUE TITLE
World save lag

### ISSUE THREAD

**Issue by Landstryder** [NightKosh/Gravestone-mod-Extended#127]
Getting massive lag spikes every 30 seconds or so and console spam of can't keep up (even in when no one has login to the server). Rolling back to 1.3.0b4 does not seem to help for worlds that were spawned using 1.3.0b5 but starting a fresh world with 1.3.0b4 has none of these issues. Discovered it was this mod by disabling and re-enabling one mod at a time and using Tickprofiler mod to figure out what mod was causing the issues

Forge Version:
14.23.2.2624

Mod Version:
GraveStone-1.12.2-Extended-1.3.0b5

 Sample of console spam:
: [09:13:04] [main/INFO]: [CHAT] The server appears to have lag spiked.
[09:13:04] [main/INFO]: [CHAT] Last tick 0.20521976s ago."Server thread" RUNNABLE
[09:13:04] [main/INFO]: [CHAT]     at net.minecraftforge.common.DimensionManager.saveDimensionDataMap(DimensionManager.java:390)
[09:13:04] [main/INFO]: [CHAT]     at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:542)
[09:13:04] [main/INFO]: [CHAT]     at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:394)
[09:13:04] [main/INFO]: [CHAT]     at net.minecraft.world.storage.SaveHandler.func_75755_a(SaveHandler.java:141)
[09:13:04] [main/INFO]: [CHAT]     at net.minecraft.world.chunk.storage.AnvilSaveHandler.func_75755_a(AnvilSaveHandler.java:40)
[09:13:04] [main/INFO]: [CHAT]     at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:1051)
[09:13:04] [main/INFO]: [CHAT]     at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1000)
[09:13:04] [main/INFO]: [CHAT]     at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408)
[09:13:04] [main/INFO]: [CHAT]     at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:252)
[09:13:04] [main/INFO]: [CHAT]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:689)
[09:13:04] [main/INFO]: [CHAT]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[09:13:04] [main/INFO]: [CHAT]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[09:13:04] [main/INFO]: [CHAT]     at java.lang.Thread.run(Unknown Source)
[09:13:04] [main/INFO]: [CHAT] 
[09:13:04] [main/INFO]: [CHAT] 
[09:13:08] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4803ms behind, skipping 96 tick(s)

Second sample with different world seed:
[09:20:02] [main/INFO]: [CHAT] The server appears to have lag spiked.
[09:20:02] [main/INFO]: [CHAT] Last tick 0.2267657s ago."Server thread" RUNNABLE
[09:20:02] [main/INFO]: [CHAT]     at java.util.IdentityHashMap.get(Unknown Source)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraftforge.registries.GameData$BlockCallbacks$1.get(GameData.java:344)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraftforge.registries.GameData$BlockCallbacks$1.func_148747_b(GameData.java:339)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraft.world.chunk.BlockStateContainer.func_186017_a(BlockStateContainer.java:136)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:324)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:252)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:689)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[09:20:02] [main/INFO]: [CHAT]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[09:20:02] [main/INFO]: [CHAT]     at java.lang.Thread.run(Unknown Source)

**Comment by Lunetouche** [comment]
Just to make this really confusing, if the world is started with b5 its broken, if its started with b4 its fine
if you start with b5 and go to b4 its broken, but if you start with b4 and go to b5 its fine.

**Comment by Lunetouche** [comment]
Poking at things ive found that worlds created with b5 have an obscenely large array in the level.dat under forge->DimensionData->DimensionArray
In the b5 worlds this has 46445271 integers, while in the b4 its only 1

I was able to reproduce this with JUST this mod and dependencies installed.

**Comment by NightKosh** [comment]
Hello. 
It looks like the reason of this problem in huge value for new dimension id. So it can be fixed even on b5 version - just change "CatacombsDimensionId" to "-8"(or any other small value) in configuration file. At least it helped me to reduce "level.dat" file size to its normal size (24kb)
Please try it and give me a feedback.

**Comment by AdaraChristine** [comment]
Hi NightKosh ,I too am currently testing this problem with my pack Mystical Village 2. I disabled the catacombs and it fixed it. But..I want to use the feature so i hope i can help. Here is the console output on a new world. I hope it helps
[19:15:55] [pool-3-thread-1/WARN] [ivtoolkit]: Did not find fitting component fo
r maze!
[19:15:55] [pool-3-thread-1/WARN] [ivtoolkit]: Suggested: X with exits [MazePass
age{source=[9, 8, 13], dest=[10, 8, 13]}=Path, MazePassage{source=[10, 8, 14], d
est=[10, 8, 13]}=Wall, MazePassage{source=[10, 8, 12], dest=[10, 8, 13]}=Wall, M
azePassage{source=[10, 9, 13], dest=[10, 8, 13]}=Wall]
[19:15:55] [pool-3-thread-1/WARN] [ivtoolkit]: Did not find fitting component fo
r maze!
[19:15:55] [pool-3-thread-1/WARN] [ivtoolkit]: Suggested: X with exits [MazePass
age{source=[12, 8, 11], dest=[12, 8, 12]}=Path, MazePassage{source=[12, 9, 12],
dest=[12, 8, 12]}=Wall]

**Comment by AdaraChristine** [comment]
Greetings NightKosh, 
I too am having this problem with my modpack. I changed the dim to -8 but did not help. Of course disabling catacombs fixes it, but i would rather use this feature. Looking forward to a fix.
Thanks!

**Comment by NightKosh** [comment]
@AdaraChristine Did you tried it with already created world or with new one?

**Comment by AdaraChristine** [comment]
NightKosh, Ive created a new world with the update and ran it all night, seems to work ok now! :) 
Thanks for your work!
