### ISSUE TITLE
Villager corpses - IllegalArgumentException

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#153]
```
java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Unknown Source)
    at net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession.getRandomCareer(VillagerRegistry.java:234)
    at nightkosh.gravestone_extended.item.corpse.VillagerCorpseHelper.getDefaultCorpses(VillagerCorpseHelper.java:62)
    at nightkosh.gravestone_extended.item.corpse.CorpseHelper.getDefaultCorpse(CorpseHelper.java:127)
    at nightkosh.gravestone_extended.block.BlockCorpse.getSubBlocks(BlockCorpse.java:75)
    at net.minecraft.item.ItemBlock.getSubItems(ItemBlock.java:149)
    at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:586)
    at net.minecraft.client.Minecraft.init(Minecraft.java:528)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3929)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by NightKosh** [comment]
@Sunconure11 unfortunately it looks like there aren't any correct ways to fix it without some changes in "MinecraftForge" code https://github.com/MinecraftForge/MinecraftForge/issues/5118

**Comment by NightKosh** [comment]
@Sunconure11 try this version please https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2608802

**Comment by Sunconure11** [comment]
I think it works, but I have stumbled upon this now.

https://paste.dimdev.org/nikeduneni.mccrash

**Comment by NightKosh** [comment]
Do you know how it can be reproduced?

**Comment by Sunconure11** [comment]
Foamfix + Your mod, as far as I can tell.

**Comment by Sunconure11** [comment]
Yeah okay it was probably my config.

**Comment by NightKosh** [comment]
So, you found the reason of this problem, didn't you? If not, the only thing I can suggest, it can be happened as a result of of these changes #152 https://github.com/NightKosh/Gravestone-mod-Extended/commit/6d8157052f919824c328d4bf689208d691455d6c#diff-4ef4fa79add068bbb9ed91851e38235d

**Comment by Sunconure11** [comment]
Yes, involving the config to turn on parallel model baking in FoamFix causes errors.
