### ISSUE TITLE
Crashing when open inventory with jei- Horse corpse render?

### ISSUE THREAD

**Issue by cjser** [NightKosh/Gravestone-mod-Extended#158]
```
Time: 2018-09-07 17:12:14 ART
Description: Rendering item

java.lang.NullPointerException
    at net.minecraft.client.model.ModelHorse.setLivingAnimations(SourceFile:367)
    at nightkosh.gravestone_extended.renderer.tileentity.CorpseRendererHelper.renderCorpse(CorpseRendererHelper.java:219)
    at nightkosh.gravestone_extended.renderer.tileentity.CorpseRendererHelper.renderCorpse(CorpseRendererHelper.java:101)
    at nightkosh.gravestone_extended.renderer.tileentity.CorpseRendererHelper.renderCorpse(CorpseRendererHelper.java:97)
    at nightkosh.gravestone_extended.renderer.item.TEISRCorpse.renderByItem(TEISRCorpse.java:37)
    at net.minecraft.client.renderer.RenderItem.renderItem(RenderItem.java:189)
    at net.minecraft.client.renderer.RenderItem.renderItemModelIntoGUI(RenderItem.java:508)
    at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:550)
    at net.minecraft.client.renderer.LCRenderItem.renderItemAndEffectIntoGUI(LCRenderItem.java:303)
    at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:28)
    at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:21)
    at mezz.jei.render.IngredientRenderer.renderSlow(IngredientRenderer.java:68)
    at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:188)
    at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:94)
    at mezz.jei.gui.overlay.IngredientGridAll.draw(IngredientGridAll.java:89)
    at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:176)
    at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:51)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1925_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.client.gui.GuiScreen.drawDefaultBackground(GuiScreen.java:575)
    at net.minecraft.client.gui.inventory.GuiInventory.drawScreen(SourceFile:66)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
    at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:654)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1456)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1118)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

**Comment by drakray** [comment]
I got that too https://pastebin.com/P5SSfeE1
It's not always though, sometime I restart the game, and it magically work.
Could it be a registering problem?
Also, @cjser you should consider Pastebin/another or simply uploading your crashlog, to make reading easier.

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/gravestone-mod-extended/files/2617789
