### ISSUE TITLE
1.9.4

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#17]

**Comment by NightKosh** [comment]
07164607cf2a5f8184fdbd4e425bed4412eff39b

**Comment by NightKosh** [comment]
__FIXED__
```
java.lang.NullPointerException: Exception ticking world
	at net.minecraft.network.datasync.EntityDataManager.set(EntityDataManager.java:136)
	at nightkosh.gravestone_extended.entity.monster.EntityUndeadHorse.setHorseArmorStack(EntityUndeadHorse.java:373)
	at net.minecraft.entity.passive.EntityHorse.updateHorseSlots(EntityHorse.java:473)
	at net.minecraft.entity.passive.EntityHorse.initHorseChest(EntityHorse.java:458)
	at net.minecraft.entity.passive.EntityHorse.<init>(EntityHorse.java:114)
	at nightkosh.gravestone_extended.entity.monster.EntityUndeadHorse.<init>(EntityUndeadHorse.java:68)
	at nightkosh.gravestone_extended.entity.monster.EntitySkeletonHorse.<init>(EntitySkeletonHorse.java:17)
	at nightkosh.gravestone_extended.entity.monster.EntitySkeletonRaider.onInitialSpawn(EntitySkeletonRaider.java:22)
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:159)
	at net.minecraft.world.WorldServer.tick(WorldServer.java:206)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:771)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:686)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:155)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:535)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by NightKosh** [comment]
__FIXED__
```
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class nightkosh.gravestone_extended.block.enums.EnumExecution, values=[GALLOWS, GIBBET, STOCKS, BURNING_STAKE]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:200) ~[BlockStateContainer$StateImplementation.class:?]
	at nightkosh.gravestone_extended.block.BlockExecution.getBoundingBox(BlockExecution.java:77) ~[BlockExecution.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getBoundingBox(BlockStateContainer.java:451) ~[BlockStateContainer$StateImplementation.class:?]
	at net.minecraft.block.Block.getCollisionBoundingBox(Block.java:460) ~[Block.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getCollisionBoundingBox(BlockStateContainer.java:441) ~[BlockStateContainer$StateImplementation.class:?]
	at net.minecraft.world.World.canBlockBePlaced(World.java:3388) ~[World.class:?]
	at net.minecraft.item.ItemBlock.onItemUse(ItemBlock.java:55) ~[ItemBlock.class:?]
	at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:157) ~[ItemStack.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.processRightClickBlock(PlayerControllerMP.java:477) ~[PlayerControllerMP.class:?]
	at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1602) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.processKeyBinds(Minecraft.java:2273) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.runTickKeyboard(Minecraft.java:2057) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1845) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:404) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
```

**Comment by NightKosh** [comment]
__FIXED__
```
[19:25:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[19:25:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.network.datasync.EntityDataManager.set(EntityDataManager.java:136)
[19:25:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at nightkosh.gravestone_extended.entity.monster.EntityUndeadHorse.setHorseArmorStack(EntityUndeadHorse.java:373)
[19:25:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.entity.passive.EntityHorse.updateHorseSlots(EntityHorse.java:473)
[19:25:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.entity.passive.EntityHorse.initHorseChest(EntityHorse.java:458)
[19:25:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.entity.passive.EntityHorse.<init>(EntityHorse.java:114)
[19:25:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at nightkosh.gravestone_extended.entity.monster.EntityUndeadHorse.<init>(EntityUndeadHorse.java:68)
[19:25:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at nightkosh.gravestone_extended.entity.monster.EntitySkeletonHorse.<init>(EntitySkeletonHorse.java:17)
[19:25:38] [Server thread/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 17 more
[19:25:38] [Server thread/ERROR] [GraveStone-Extended]: getForeinMob NullPointerException. mob name GraveStone-Extended.skeletonhorse
[19:25:38] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:788) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:686) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:155) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:535) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at nightkosh.gravestone_extended.core.MobSpawn.getForeinMob(MobSpawn.java:217) ~[MobSpawn.class:?]
	at nightkosh.gravestone_extended.core.MobSpawn.getMobEntityForSpawner(MobSpawn.java:163) ~[MobSpawn.class:?]
	at nightkosh.gravestone_extended.tileentity.MobSpawner.getMob(MobSpawner.java:105) ~[MobSpawner.class:?]
	at nightkosh.gravestone_extended.tileentity.MobSpawner.serverUpdateLogic(MobSpawner.java:55) ~[MobSpawner.class:?]
	at nightkosh.gravestone_extended.tileentity.Spawner.update(Spawner.java:38) ~[Spawner.class:?]
	at nightkosh.gravestone_extended.tileentity.TileEntitySpawner.update(TileEntitySpawner.java:32) ~[TileEntitySpawner.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1942) ~[World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:645) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:782) ~[MinecraftServer.class:?]
	... 4 more
```
