### ISSUE TITLE
Crash during initialization w/ Advanced Fishing and Extended

### ISSUE THREAD

**Issue by ghost** [NightKosh/Gravestone-mod-Extended#176]
Hello! I am returning to Minecraft from a bit of a hiatus, and I am in the process of updating mods. I see that Advanced Fishing has been added as a required mod for this mod. For some reason, I can't get it to install properly. If Advanced Fishing is installed by itself, everything runs fine. Once I add in the Gravestone mods, I get an error.

 

The game crashed whilst initializing game
Error: java.lang.NoSuchFieldError: SPECULAR_FISH

 

Advanced Fishing 1.12.2-1.3.2

Gravestone 1.12.2-1.3.0

Gravestone Extended 1.12.2-1.3.0b12

Forge 1.12.2-14.23.5.2768

Full crash report:
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 11/1/18 7:36 PM
Description: Initializing game

java.lang.NoSuchFieldError: SPECULAR_FISH
	at nightkosh.gravestone_extended.core.GSPotion.registerPotionTypes(GSPotion.java:77)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_GSPotion_registerPotionTypes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at nightkosh.gravestone_extended.core.GSPotion.registerPotionTypes(GSPotion.java:77)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_GSPotion_registerPotionTypes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 798848704 bytes (761 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2769 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version      | Source                                  | Signature                                |
	|:----- |:------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft           | 1.12.2       | minecraft.jar                           | None                                     |
	| UCH   | mcp                 | 9.42         | minecraft.jar                           | None                                     |
	| UCH   | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2769.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge               | 14.23.5.2769 | forge-1.12.2-14.23.5.2769.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | advanced-fishing    | 1.3.2        | Advanced-Fishing-1.12.2-1.3.2.jar       | None                                     |
	| UCH   | gravestone          | 1.3.0        | GraveStone-1.12.2-Graves-1.3.0.jar      | None                                     |
	| UCH   | gravestone-extended | 1.3.0b12     | GraveStone-1.12.2-Extended-1.3.0b12.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.16' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.16, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge,LiteLoader'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz

**Comment by NightKosh** [comment]
Why did you used outdated beta version 1.3.0b12 instead of latest 1.3.1 ?
https://minecraft.curseforge.com/projects/gravestone-mod-extended/files

**Comment by ghost** [comment]
I wish I could answer that because I'm not sure why I downloaded that version. I downloaded everything yesterday, so I definitely should have downloaded 1.3.1.

Now that I think about it, I was looking through the changelogs, and I must not have not been paying enough attention and thought I was downloading the latest version. That is my best guess at least. 

I will definitely download the correct version when I get back to my game. Sorry to waste your time. I should have been paying more attention.
