### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nexusdog** [NightKosh/Gravestone-mod-Extended#195]
MC/F 1.12.2/2769
Gravestone Extended v 1.3.5.1
Graves 1.3.1

https://gist.github.com/Nexusdog/bdaa63bb77b7e29f8861fe41677c644f

Tried to move villager corpse from storage (actually additions small crate)  into main inventory (cyclic extended inventory). 

```
java.lang.NullPointerException
    at nightkosh.gravestone_extended.item.corpse.VillagerCorpseHelper.getNotVanillaVillagerProfession(VillagerCorpseHelper.java:266)
    at nightkosh.gravestone_extended.item.corpse.VillagerCorpseHelper.getVillagerProfession(VillagerCorpseHelper.java:198)
    at nightkosh.gravestone_extended.item.corpse.VillagerCorpseHelper.getProfession(VillagerCorpseHelper.java:168)
    at nightkosh.gravestone_extended.item.corpse.VillagerCorpseHelper.addInfo(VillagerCorpseHelper.java:149)
    at nightkosh.gravestone_extended.item.corpse.CorpseHelper.addInfo(CorpseHelper.java:80)
    at nightkosh.gravestone_extended.item.itemblock.IBCorpse.addInformation(IBCorpse.java:45)
    at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:707)
    at net.minecraft.client.gui.GuiScreen.getItemToolTip(GuiScreen.java:143)
    at net.minecraft.client.gui.GuiScreen.renderToolTip(GuiScreen.java:137)
    at net.minecraft.client.gui.inventory.GuiContainer.renderHoveredToolTip(GuiContainer.java:175)
    at de.ellpeck.actuallyadditions.mod.inventory.gui.GuiWtfMojang.drawScreen(GuiWtfMojang.java:26)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by NightKosh** [comment]
Do you remember what kind of villager it was?

**Comment by Nexusdog** [comment]
It didn't seem to be specific to one particular villager - it happened multiple times with different villagers. However, they were a mix of both, I started moving out whatever came first, which happened to be non vanilla types.
