### ISSUE TITLE
Crash while exploring a catacombs

### ISSUE THREAD

**Issue by Scratchman** [NightKosh/Gravestone-mod-Extended#23]
Thanks for updating the mod, I really look forward to adding this to our 1.10.2 server. :)

Had this crash happen in single player while i was exploring a new catacombs.

https://pastebin.com/PgZvcC4M

**Comment by NightKosh** [comment]
```
java.lang.NullPointerException: Saving entity NBT
    at nightkosh.gravestone_extended.entity.monster.pet.EntityUndeadPet.func_70014_b(EntityUndeadPet.java:146)
    at net.minecraft.entity.Entity.func_189511_e(Entity.java:1582)
    at mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData(DataAccessorCommon.java:158)
    at net.darkhax.wawla.engine.waila.EntityProvider.getWailaOverride(EntityProvider.java:22)
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierEntity(RayTracing.java:115)
    at mcp.mobius.waila.overlay.RayTracing.getTargetEntity(RayTracing.java:71)
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:100)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_912_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Client thread
Stacktrace:
    at nightkosh.gravestone_extended.entity.monster.pet.EntityUndeadPet.func_70014_b(EntityUndeadPet.java:146)
 
-- Entity being saved --
Details:
    Entity Type: GraveStone-Extended.GSSkeletonCat (nightkosh.gravestone_extended.entity.monster.pet.EntitySkeletonCat)
    Entity ID: 49690
    Entity Name: entity.GraveStone-Extended.GSSkeletonCat.name
    Entity's Exact location: 2064.60, 18.00, 226.79
    Entity's Block location: World: (2064,18,226), Chunk: (at 0,1,2 in 129,14; contains blocks 2064,0,224 to 2079,255,239), Region: (4,0; contains chunks 128,0 to 159,31, blocks 2048,0,0 to 2559,255,511)
    Entity's Momentum: 0.00, 0.00, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
```
