### ISSUE TITLE
Graves and memorials crafting

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Gravestone-mod-Extended#3]
https://github.com/NightKosh/Gravestone-mod-Graves/issues/190

**Comment by NightKosh** [comment]
```
java.lang.NullPointerException: Updating screen events
	at nightkosh.gravestone_extended.crafting.GravestoneRecipe.getResultItem(GravestoneRecipe.java:61)
	at nightkosh.gravestone_extended.crafting.GravestoneRecipe.getResultItem(GravestoneRecipe.java:50)
	at nightkosh.gravestone_extended.crafting.GravesCraftingManager.findMatchingRecipe(GravesCraftingManager.java:79)
	at nightkosh.gravestone_extended.gui.container.ChiselContainer.onCraftMatrixChanged(ChiselContainer.java:93)
	at net.minecraft.inventory.InventoryCrafting.setInventorySlotContents(InventoryCrafting.java:119)
	at net.minecraft.inventory.Slot.putStack(Slot.java:97)
	at net.minecraft.inventory.Container.slotClick(Container.java:220)
	at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:610)
	at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:693)
	at net.minecraft.client.gui.inventory.GuiContainer.mouseReleased(GuiContainer.java:632)
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:621)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:576)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1884)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1186)
	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)
```
